### gets all games
GET  http://localhost:5042/games

### gets specific game
GET  http://localhost:5042/games/0

### adds new game
POST http://localhost:5042/games 
Content-Type: application/json

{
    "name":"as",
    "genre": "Kids and Family",
    "price":19.99,
    "releaseDate":"2011-11-18"
}

### updates a game
PUT http://localhost:5042/games/1
Content-Type: application/json

{
    "name":"Street Fighter III Turbo",
    "genre": "Fighting",
    "price":9.99,
    "releaseDate":"1995-11-18"
}

### delete a game
DELETE http://localhost:5042/games/1

